services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5430:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
volumes:
  postgres: {}